apiVersion: batch/v1
kind: CronJob
metadata:
  name: metallb-dyndns
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10800
      backoffLimit: 3
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: metallb-dyndns
              image: yonggan/metallb-dyndns:latest
          restartPolicy: Never
